version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zebra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
      SERVER_MODE: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: zebra
      DB_SSLMODE: disable
      JWT_SECRET: your-super-secret-key-change-this
      JWT_EXPIRY_MINUTES: 1440
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  fileserver:
    build:
      context: .
      dockerfile: ./cmd/fileserver/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=zebra
      - DB_PORT=5432
      - GIN_MODE=debug
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
